#!/usr/bin/env python3
"""Assign every XC7A50T-CSG325 ball, from the AMD package file. Reproducible:
    python3 tools/ballmap.py > ref/ballmap.md
Source of truth: ref/xc7a50tcsg325pkg.txt (xilinx.com/support/packagefiles/a7packages).
"""
import re, sys
from collections import defaultdict, OrderedDict

PKG = 'ref/xc7a50tcsg325pkg.txt'

def load():
    io = defaultdict(list)      # bank -> [(ball, name)]
    other = defaultdict(list)
    for l in open(PKG, encoding='utf-8', errors='replace'):
        l = l.replace('\r', '').rstrip()
        if not l.strip() or l.startswith(('Device/Package', 'Pin ')): continue
        f = re.split(r'\s{2,}', l.strip())
        if len(f) < 7: continue
        ball, name, _, bank, _, _, iot = f[:7]
        (io if iot == 'HR' else other)[bank].append((ball, name))
    return io, other

def pairs_and_singles(pins):
    """-> (ordered list of (P_ball,N_ball,idx), ordered list of single balls)"""
    p = defaultdict(dict)
    single = []
    for ball, name in pins:
        m = re.match(r'IO_L(\d+)([PN])_T(\d+)', name)
        if m: p[int(m.group(1))][m.group(2)] = ball
        else: single.append(ball)
    full = [(v['P'], v['N'], k) for k, v in sorted(p.items()) if len(v) == 2]
    half = [b for v in p.values() if len(v) == 1 for b in v.values()]
    return full, single + half

# config-critical bank 14 balls we must not hand to anything else
CONFIG_USE = OrderedDict([
    ('K16', 'FLASH_D0_MOSI'), ('L17', 'FLASH_D1_MISO'),
    ('J15', 'FLASH_D2_WP'),   ('J16', 'FLASH_D3_HOLD'),
    ('L15', 'FLASH_CS_B'),    ('J18', 'PUDC_B'),
])

def take(pool_pairs, pool_single, n_pairs, n_single, used):
    got_p, got_s = [], []
    while len(got_p) < n_pairs and pool_pairs:
        a, b, i = pool_pairs.pop(0)
        if a in used or b in used: continue
        used.update((a, b)); got_p.append((a, b, i))
    while len(got_s) < n_single and pool_single:
        b = pool_single.pop(0)
        if b in used: continue
        used.add(b); got_s.append(b)
    return got_p, got_s

def main():
    io, other = load()
    used = set(CONFIG_USE)
    out = []
    W = out.append

    W("# XC7A50T-CSG325 ball map\n")
    W("Generated by `tools/ballmap.py` from `ref/xc7a50tcsg325pkg.txt`")
    W("(AMD package file, `xc7a50tcsg325`, dated 2013-12-03). Regenerate with:\n")
    W("```\npython3 tools/ballmap.py > ref/ballmap.md\n```\n")

    W("## The constraint that shapes everything\n")
    tot = sum(len(v) for v in io.values())
    W(f"This package has **three HR I/O banks** — 14, 15 and 34 — {tot} user I/O total.")
    W("Not five. `VCCO` is per bank, so **three is the hard ceiling on independent")
    W("I/O voltage domains**, and one of them is spoken for.\n")
    W("| Bank | HR I/O | Diff pairs | MRCC | SRCC |")
    W("|---|---|---|---|---|")
    for bk in ('14', '15', '34'):
        fp, sg = pairs_and_singles(io[bk])
        mr = sum('MRCC' in n for _, n in io[bk]); sr = sum('SRCC' in n for _, n in io[bk])
        W(f"| {bk} | {len(io[bk])} | {len(fp)} | {mr} | {sr} |")
    W("")
    W("**Bank 14 is not free.** It carries the master-SPI config flash pins")
    W("(`D00_MOSI`, `D01_DIN`, `D02`, `D03`, `FCS_B`) and the `PUDC_B` strap, so its")
    W("`VCCO` is pinned at 3.3V by the flash. That makes it the natural home for")
    W("everything else that is fixed at 3.3V, and leaves **banks 15 and 34 as the")
    W("only two settable domains.**\n")

    W("## Allocation\n")
    W("| Bank | VCCO | Contents |")
    W("|---|---|---|")
    W("| 14 | **fixed 3.3V** | config flash, PSRAM ×4, supervisor sideband, slot L (buffered) |")
    W("| 15 | **settable** 3.3 / 2.5 / 1.8 | slots A B C D |")
    W("| 34 | **settable** 3.3 / 2.5 / 1.8 | slots E F G H |")
    W("")

    # ---- bank 14
    fp14, sg14 = pairs_and_singles(io['14'])
    fp14 = [t for t in fp14 if t[0] not in used and t[1] not in used]
    sg14 = [b for b in sg14 if b not in used]

    W("## Bank 14 — fixed 3.3V\n")
    W("### Config flash (master SPI, quad)\n")
    W("| Ball | Net | Package name |")
    W("|---|---|---|")
    names14 = dict(io['14'])
    for ball, net in CONFIG_USE.items():
        W(f"| {ball} | `{net}` | {names14.get(ball,'')} |")
    W("")
    W("`CCLK`, `PROGRAM_B`, `INIT_B`, `DONE`, `M[2:0]`, `TCK/TMS/TDI/TDO` are bank 0")
    W("dedicated pins — see the bank 0 table at the end.\n")

    W("### PSRAM — four independent QSPI buses\n")
    W("Six pins per chip: `SCK`, `CE#`, `IO0..IO3`. Independent, per `ref/psram.md`.\n")
    W("| Chip | SCK | CE# | IO0 | IO1 | IO2 | IO3 |")
    W("|---|---|---|---|---|---|---|")
    psram = {}
    for c in range(4):
        gp, gs = take(fp14, sg14, 3, 0, used)
        balls = [b for pr in gp for b in pr[:2]]
        psram[c] = balls
        W(f"| PSRAM{c} | {balls[0]} | {balls[1]} | {balls[2]} | {balls[3]} | {balls[4]} | {balls[5]} |")
    W("")
    W("Each chip's six lines are taken from three adjacent differential pairs, so the")
    W("group is physically tight on the die edge and length-matching stays local.\n")

    W("### Supervisor sideband\n")
    gp, gs = take(fp14, sg14, 3, 0, used)
    sb = [b for pr in gp for b in pr[:2]]
    sbnets = ['DBG_TCK', 'DBG_TMS', 'DBG_TDI', 'DBG_TDO', 'SB_UART_RX', 'SB_UART_TX']
    W("| Ball | Net | Purpose |")
    W("|---|---|---|")
    purp = ['NEORV32 debug JTAG', 'NEORV32 debug JTAG', 'NEORV32 debug JTAG',
            'NEORV32 debug JTAG', 'fabric UART from supervisor', 'fabric UART to supervisor']
    for b, n, p in zip(sb, sbnets, purp): W(f"| {b} | `{n}` | {p} |")
    W("")

    W("### Slot L — buffered, 5V-tolerant\n")
    W("The level-shifted slot lives here because bank 14 is pinned at 3.3V anyway.")
    W("Costs no settable domain. `SN74LXCH8T245` between the balls and the connector.\n")
    slots = OrderedDict()
    gp, gs = take(fp14, sg14, 5, 0, used)
    slots['L'] = ('14', gp, gs)

    # ---- banks 15 and 34
    for bk, names in (('15', 'ABCD'), ('34', 'EFGH')):
        fp, sg = pairs_and_singles(io[bk])
        for s in names:
            gp, gs = take(fp, sg, 5, 0, used)
            slots[s] = (bk, gp, gs)

    W("## Extension slot ball assignment\n")
    W("Ten I/O per slot, allocated as **five true differential pairs** — one per")
    W("connector column, so `P+`/`P-` are vertically adjacent on the header. Single-")
    W("ended users just call them `IO0..IO9`; nothing is wasted either way.\n")
    W("| Slot | Bank | P0+ | P0- | P1+ | P1- | P2+ | P2- | P3+ | P3- | P4+ | P4- |")
    W("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for s, (bk, gp, gs) in slots.items():
        b = [x for pr in gp for x in pr[:2]]
        W(f"| **{s}** | {bk} | " + " | ".join(b) + " |")
    W("")
    W("Slot L is buffered; A–H are direct. See `ref/extension-ux.md`.\n")

    W("## Bank 0 — dedicated configuration pins\n")
    W("| Ball | Name |")
    W("|---|---|")
    for ball, name in sorted(other['0']): W(f"| {ball} | `{name}` |")
    W("")

    W("## Bank 216 — four GTP transceivers\n")
    W("**These cannot be added later.** A 6.6 Gb/s lane will not survive a 0.1\" pin")
    W("header, so if they are not brought to a proper connector on the base board")
    W("now, the silicon is wasted for the life of the design.\n")
    W("| Ball | Name |")
    W("|---|---|")
    for ball, name in sorted(other['216']): W(f"| {ball} | `{name}` |")
    W("")

    W("## Budget\n")
    W(f"- assigned: **{len(used)}** of {tot} HR I/O")
    W(f"- free: **{tot - len(used)}** for base-board peripherals (VGA, buttons, LEDs, audio)")
    W("- 4 GTP lanes, unassigned, decision pending")
    print("\n".join(out))

main()
