#!/usr/bin/env python3
"""Render ref/ballmap.md from tools/alloc.py — the single allocation source.
    python3 tools/ballmap.py > ref/ballmap.md
Facts come from ref/xc7a50tcsg325pkg.txt (AMD package file)."""
import sys, os, re
sys.path.insert(0, os.path.dirname(__file__))
from alloc import assign, load, pairs_and_singles, CONFIG_USE, SIDEBAND
from collections import defaultdict

def main():
    net, psram, sb, slots, io, other = assign()
    tot = sum(len(v) for v in io.values())
    o = []; W = o.append

    W("# XC7A50T-CSG325 ball map\n")
    W("Generated by `tools/ballmap.py` from `tools/alloc.py`, which is the one")
    W("place ball allocation is decided. The schematic is generated from the same")
    W("function, so this file and the circuit cannot disagree. Package facts come")
    W("from `ref/xc7a50tcsg325pkg.txt` (AMD, `xc7a50tcsg325`, 2013-12-03).\n")
    W("```\npython3 tools/ballmap.py > ref/ballmap.md\n```\n")

    W("## The constraint that shapes everything\n")
    W(f"This package has **three HR I/O banks** — 14, 15 and 34 — {tot} user I/O total.")
    W("`VCCO` is per bank, so **three is the hard ceiling on independent I/O voltage")
    W("domains**, and one of them is spoken for.\n")
    W("| Bank | HR I/O | Diff pairs | MRCC | SRCC |")
    W("|---|---|---|---|---|")
    for bk in ('14', '15', '34'):
        fp, _ = pairs_and_singles(io[bk])
        mr = sum('MRCC' in n for _, n in io[bk]); sr = sum('SRCC' in n for _, n in io[bk])
        W(f"| {bk} | {len(io[bk])} | {len(fp)} | {mr} | {sr} |")
    W("")
    W("**Bank 14 is not free.** It carries the master-SPI config flash pins and the")
    W("`PUDC_B` strap, so its `VCCO` is pinned at 3.3V by the flash. That makes it")
    W("the home for everything else fixed at 3.3V — PSRAM, the supervisor sideband,")
    W("and the level-shifted slot L — and leaves **banks 15 and 34 as the only two")
    W("settable domains**, four slots each.\n")

    W("## Allocation\n")
    W("| Bank | VCCO | Contents |")
    W("|---|---|---|")
    W("| 14 | **fixed 3.3V** | config flash, PSRAM x4, supervisor sideband, slot L + its 2 direction pins |")
    W("| 15 | **settable** 3.3 / 2.5 / 1.8 | slots A B C D |")
    W("| 34 | **settable** 3.3 / 2.5 / 1.8 | slots E F G H |")
    W("")

    names = {b: n for lst in list(io.values()) + list(other.values()) for b, n in lst}
    groups = defaultdict(list)
    for ball, n in sorted(net.items()):
        if n.startswith('SLOT') and '_DIR' not in n: groups['slots'].append((ball, n))
        elif n.startswith('SLOTL_DIR'): groups['slot L direction'].append((ball, n))
        elif n.startswith('PSRAM'): groups['PSRAM'].append((ball, n))
        elif n in CONFIG_USE.values(): groups['config flash + strap'].append((ball, n))
        else: groups['supervisor sideband'].append((ball, n))

    W("## Config flash and strap\n")
    W("| Ball | Net | Package name |")
    W("|---|---|---|")
    for ball, n in CONFIG_USE.items(): W(f"| {ball} | `{n}` | {names.get(ball,'')} |")
    W("\n`CCLK`, `PROGRAM_B`, `INIT_B`, `DONE`, `M[2:0]` and JTAG are bank 0")
    W("dedicated pins — see the bank 0 table below.\n")

    W("## PSRAM — four independent QSPI buses\n")
    W("| Chip | SCK | CE# | IO0 | IO1 | IO2 | IO3 |")
    W("|---|---|---|---|---|---|---|")
    for c, balls in psram.items(): W(f"| PSRAM{c} | " + " | ".join(balls) + " |")
    W("\nEach chip's six lines come from three adjacent differential pairs, so the")
    W("group stays physically tight and length matching stays local.\n")

    W("## Supervisor sideband\n")
    W("| Ball | Net |")
    W("|---|---|")
    for b, n in zip(sb, SIDEBAND): W(f"| {b} | `{n}` |")
    W("")

    W("## Extension slots\n")
    W("Ten I/O per slot as **five differential pairs**, one per connector column,")
    W("so `P+`/`P-` are vertically adjacent on the header. Single-ended users just")
    W("call them `IO0..IO9`.\n")
    W("| Slot | Bank | P0+ | P0- | P1+ | P1- | P2+ | P2- | P3+ | P3- | P4+ | P4- |")
    W("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for s, (bk, prs) in slots.items():
        W(f"| **{s}** | {bk} | " + " | ".join(b for pr in prs for b in pr) + " |")
    W("")
    dirs = groups['slot L direction']
    W(f"Slot L is buffered; A–H are direct. Slot L additionally uses "
      f"{', '.join(b for b, _ in dirs)} for the two translator direction controls, "
      f"so it costs **12** I/O for 10 connector signals.\n")

    W("## Bank 0 — dedicated configuration pins\n")
    W("| Ball | Name |")
    W("|---|---|")
    for ball, name in sorted(other['0']): W(f"| {ball} | `{name}` |")
    W("")
    W("## Bank 216 — four GTP transceivers\n")
    W("Lanes 0 and 1 go to populated SFP cages, 2 and 3 to unpopulated footprints.")
    W("See `ref/highspeed.md`.\n")
    W("| Ball | Name |")
    W("|---|---|")
    for ball, name in sorted(other['216']): W(f"| {ball} | `{name}` |")
    W("")

    W("## Budget\n")
    for k in ('slots', 'PSRAM', 'supervisor sideband', 'config flash + strap',
              'slot L direction'):
        W(f"- {k}: **{len(groups[k])}**")
    W(f"- **assigned: {len(net)} of {tot}**")
    W(f"- **free: {tot - len(net)}** for base-board peripherals")
    print("\n".join(o))

main()
