#!/usr/bin/env python3
"""Render ref/ballmap.md from tools/alloc.py — the single allocation source.
    python3 tools/ballmap.py > ref/ballmap.md
Package facts come from the imported EasyEDA/LCSC symbol."""
import sys, os, re
sys.path.insert(0, os.path.dirname(__file__))
from alloc import assign, load, pairs_and_singles, CONFIG_USE, SIDEBAND
from collections import defaultdict

def main():
    net, psram, sb, slots, io, other = assign()
    tot = sum(len(v) for v in io.values())
    o = []; W = o.append

    W("# XC7A100T-FGG676 ball map\n")
    W("Generated by `tools/ballmap.py` from `tools/alloc.py`, which is the one")
    W("place ball allocation is decided. The schematic is generated from the same")
    W("function, so this file and the circuit cannot disagree. Package facts come")
    W("from the imported `XC7A100T-2FGG676I` symbol, LCSC `C1521803`.\n")
    W("```\npython3 tools/ballmap.py > ref/ballmap.md\n```\n")

    W("## I/O-bank architecture\n")
    W(f"This package has **six HR I/O banks** — 13, 14, 15, 16, 34 and 35 — {tot} user I/O total.")
    W("`VCCO` is shared by every pin in a bank. Odin uses bank 14 at fixed 3.3V,")
    W("bank 13 for 5V BUS 1, banks 15 and 34 as selectable extension domains, and reserves")
    W("banks 16 and 35 for later base-board peripherals.\n")
    W("| Bank | HR I/O | Diff pairs | MRCC | SRCC |")
    W("|---|---|---|---|---|")
    for bk in ('13', '14', '15', '16', '34', '35'):
        fp, _ = pairs_and_singles(io[bk])
        mr = sum('MRCC' in n for _, n in io[bk]); sr = sum('SRCC' in n for _, n in io[bk])
        W(f"| {bk} | {len(io[bk])} | {len(fp)} | {mr} | {sr} |")
    W("")
    W("**Bank 14 is not free.** It carries the master-SPI config flash pins and the")
    W("`PUDC_B` strap, so its `VCCO` is pinned at 3.3V by the flash. That makes it")
    W("the home for everything else fixed at 3.3V — PSRAM, the supervisor sideband,")
    W("and 5V BUS 0. Bank 13 carries 5V BUS 1. Banks 15 and 34 are the two settable extension")
    W("domains, four slots each. The other two HR banks are powered at 3.3V but")
    W("carry no signals in this revision.\n")

    W("## Allocation\n")
    W("| Bank | VCCO | Contents |")
    W("|---|---|---|")
    W("| 14 | **fixed 3.3V** | config flash, PSRAM x4, supervisor sideband, 5V BUS 0 |")
    W("| 13 | fixed 3.3V | 5V BUS 1 |")
    W("| 15 | **settable** 3.3 / 2.5 / 1.8 | slots A B C D |")
    W("| 34 | **settable** 3.3 / 2.5 / 1.8 | slots E F G H |")
    W("| 16, 35 | fixed 3.3V | reserved for future base-board peripherals |")
    W("")

    names = {b: n for lst in list(io.values()) + list(other.values()) for b, n in lst}
    groups = defaultdict(list)
    for ball, n in sorted(net.items()):
        if n.startswith('SLOT') and '_DIR' not in n: groups['slots'].append((ball, n))
        elif n.startswith('BUS5V') and n.endswith('_DIR'): groups['5V bus direction'].append((ball, n))
        elif n.startswith('BUS5V') and n.endswith('_OE_N'): groups['5V bus enable'].append((ball, n))
        elif n.startswith('BUS5V'): groups['5V bus data'].append((ball, n))
        elif n.startswith('PSRAM'): groups['PSRAM'].append((ball, n))
        elif n in CONFIG_USE.values(): groups['config flash + strap'].append((ball, n))
        elif n in SIDEBAND: groups['supervisor sideband'].append((ball, n))
        else: raise ValueError(f'Unclassified allocated net: {ball} {n}')
    assert len(groups['supervisor sideband']) == len(sb) == len(SIDEBAND)
    assert sum(map(len, groups.values())) == len(net)

    W("## Config flash and strap\n")
    W("| Ball | Net | Package name |")
    W("|---|---|---|")
    for ball, n in CONFIG_USE.items(): W(f"| {ball} | `{n}` | {names.get(ball,'')} |")
    W("\n`CCLK`, `PROGRAM_B`, `INIT_B`, `DONE`, `M[2:0]` and JTAG are bank 0")
    W("dedicated pins — see the bank 0 table below.\n")

    W("## PSRAM — four independent QSPI buses\n")
    W("| Chip | SCK | CE# | IO0 | IO1 | IO2 | IO3 |")
    W("|---|---|---|---|---|---|---|")
    for c, balls in psram.items(): W(f"| PSRAM{c} | " + " | ".join(balls) + " |")
    W("\nEach chip's six lines come from three adjacent differential pairs, so the")
    W("group stays physically tight and length matching stays local.\n")

    W("## Supervisor sideband\n")
    W("| Ball | Net |")
    W("|---|---|")
    for b, n in zip(sb, SIDEBAND): W(f"| {b} | `{n}` |")
    W("")

    W("## Extension slots\n")
    W("Direct slots A-H expose twelve ordinary numbered I/O as six adjacent")
    W("differential-capable pairs. Pairing remains")
    W("an optional capability rather than part of the basic connector UX.")
    W("5V BUS 0 and 5V BUS 1 each expose one complete translated 8-bit bus.\n")
    W("| Slot | Bank | FPGA balls in connector order |")
    W("|---|---|---|")
    for s, (bk, prs) in slots.items():
        W(f"| **{s}** | {bk} | " + ", ".join(b for pr in prs for b in pr) + " |")
    W("")
    dirs = groups['5V bus direction']
    W(f"The two 5V buses are buffered; A-H are direct. "
      f"{', '.join(b for b, _ in dirs)} are their direction controls. "
      f"Together the buses cost **20** FPGA I/O for 16 connector signals.\n")
    W("| Bus control | FPGA ball | Bank | Default |")
    W("|---|---|---|---|")
    for ball, n in groups['5V bus enable']:
        bank = '14' if n.startswith('BUS5V0') else '13'
        W(f"| `{n}` | {ball} | {bank} | 10k to +3V3; high disables the bus |")
    W("\nHold OE_N high while setting DIR and data; drive OE_N low only when ready.")
    W("Raise OE_N again before changing direction.\n")

    W("## Bank 0 — dedicated configuration pins\n")
    W("| Ball | Name |")
    W("|---|---|")
    for ball, name in sorted(other['0']): W(f"| {ball} | `{name}` |")
    W("")
    W("## Bank 216 — two connected GTP transceivers\n")
    W("Lanes 0 and 1 go to the two SFP ports. Lanes 2 and 3 have RX grounded")
    W("and TX floating; unused reference-clock inputs float (UG482 Table 5-6).")
    W("See `ref/highspeed.md`.\n")
    W("| Ball | Name |")
    W("|---|---|")
    for ball, name in sorted(other['216']): W(f"| {ball} | `{name}` |")
    W("")
    W("## Bank 213 — unused GTP transceivers\n")
    W("The G10 supplies remain powered. All eight RX pins connect to GND;")
    W("MGTRREF_213 connects through its own 100 ohm, 1% resistor to +1V2_MGT.")
    W("TX and reference-clock pins float, per UG482 Table 5-5.\n")

    W("## Budget\n")
    for k in ('slots', 'PSRAM', 'supervisor sideband', 'config flash + strap',
              '5V bus data', '5V bus direction', '5V bus enable'):
        W(f"- {k}: **{len(groups[k])}**")
    W(f"- **assigned HR I/O: {len(net)} of {tot}**")
    W(f"- **free: {tot - len(net)}** for base-board peripherals")
    rendered = "\n".join(o) + "\n"
    if '--write' in sys.argv:
        with open('ref/ballmap.md', 'w', encoding='utf-8') as f:
            f.write(rendered)
        print('wrote ref/ballmap.md')
    else:
        print(rendered, end='')

main()
