#!/usr/bin/env python3
"""Emit an empty 6-layer kicad_pcb with outline + stackup + net classes.
Populate it in the PCB editor with Update PCB from Schematic (F8)."""
import argparse
import json
from pathlib import Path

from identity import PRODUCT, HW_VERSION, FPGA_PART, CONTROLLER_PART
W, H, R = 100.0, 100.0, 3.0        # board size and corner radius
X0, Y0 = 30.0, 30.0
OUT = 'kicad/odin.kicad_pcb'

# JLC06161H-1080B, coated outer microstrip L1/L2 or L6/L5, 100 ohm.
# JLC solver: W1=3.8828125 mil at S1=0.200 mm; round width to 0.099 mm.
# Inputs, calculation response, material table: ref/pcb-impedance.md.
MGT_WIDTH = 0.099
MGT_GAP = 0.200
MGT_PATTERNS = ('MGTP*', 'MGTREFCLK*', 'SFP?_TD_*', 'SFP?_RD_*', 'REFCLK_OSC_*')


def emit_rules():
    """Merge generated classes into the project; preserve unrelated settings."""
    path = Path(OUT).with_suffix('.kicad_pro')
    project = json.loads(path.read_text())
    settings = project['net_settings']
    default = next(c for c in settings['classes'] if c['name'] == 'Default')
    default.update(clearance=0.15, via_diameter=0.45, via_drill=0.2)
    settings['classes'] = [c for c in settings['classes']
                           if c['name'] not in ('MGT_100R', 'PSRAM')]
    settings['classes'] += [
        dict(default, name='MGT_100R', priority=0, track_width=MGT_WIDTH,
             diff_pair_width=MGT_WIDTH, diff_pair_gap=MGT_GAP),
        dict(default, name='PSRAM', priority=1, track_width=0.1),
    ]
    settings['netclass_patterns'] = [p for p in settings['netclass_patterns']
                                    if p['netclass'] not in ('MGT_100R', 'PSRAM')]
    settings['netclass_patterns'] += [dict(netclass='MGT_100R', pattern=p)
                                      for p in MGT_PATTERNS]
    settings['netclass_patterns'].append(dict(netclass='PSRAM', pattern='PSRAM*'))
    project['board']['design_settings']['rules'].update(
        min_clearance=0.15, min_track_width=0.0889,
        min_via_diameter=0.45, min_through_hole_diameter=0.2)
    path.write_text(json.dumps(project, indent=2) + '\n')
    rules = f'''# Generated by tools/gen_pcb.py; see ref/pcb-impedance.md.
(version 1)
(rule "Default clearance"
  (constraint clearance (min 0.15mm)))
(rule "PSRAM minimum width"
  (condition "A.hasNetclass('PSRAM')")
  (constraint track_width (min 0.1mm) (opt 0.1mm)))
(rule "MGT 100R outer geometry"
  (layer outer)
  (condition "A.hasNetclass('MGT_100R')")
  (constraint track_width (min {MGT_WIDTH}mm) (opt {MGT_WIDTH}mm) (max {MGT_WIDTH}mm))
  (constraint diff_pair_gap (min {MGT_GAP}mm) (opt {MGT_GAP}mm) (max {MGT_GAP}mm)))
# This geometry is calculated only for L1/L2 and L6/L5, not inner layers.
(rule "MGT outer routing only"
  (layer inner)
  (condition "A.hasNetclass('MGT_100R')")
  (constraint disallow track))
# Keep other copper >= ~4 dielectric heights away for the non-coplanar model.
(rule "MGT clearance to other copper"
  (condition "A.hasNetclass('MGT_100R') && !AB.isCoupledDiffPair()")
  (constraint clearance (min 0.31mm)))
(rule "MGT intra-pair skew"
  (condition "A.hasNetclass('MGT_100R')")
  (constraint skew (max 0.1mm) (within_diff_pairs)))
'''
    Path(OUT).with_suffix('.kicad_dru').write_text(rules)
    print(f'wrote {path} net classes and {Path(OUT).with_suffix(".kicad_dru")}')


def sexpr_block(text, marker):
    """Locate one balanced block, ignoring parentheses in quoted strings."""
    start = text.index(marker)
    depth, quoted, escaped = 0, False, False
    for i in range(start, len(text)):
        c = text[i]
        if escaped:
            escaped = False
        elif c == '\\' and quoted:
            escaped = True
        elif c == '"':
            quoted = not quoted
        elif not quoted:
            depth += (c == '(') - (c == ')')
            if depth == 0:
                return start, i + 1
    raise ValueError(f'Unterminated block: {marker}')


def update_stackup():
    """Replace only the stackup block; placement, tracks and zones stay intact."""
    path = Path(OUT)
    board = path.read_text()
    start, end = sexpr_block(board, '(stackup')
    a, b = sexpr_block(SETUP, '(stackup')
    path.write_text(board[:start] + SETUP[a:b] + board[end:])
    print(f'updated {path}: JLC06161H-1080B stackup; placement preserved')

LAYERS = [(0,'F.Cu','signal'), (1,'In1.Cu','signal','GND plane'),
          (2,'In2.Cu','signal'), (3,'In3.Cu','signal','power planes'),
          (4,'In4.Cu','signal','GND plane'), (31,'B.Cu','signal'),
          (32,'B.Adhes','user','B.Adhesive'), (33,'F.Adhes','user','F.Adhesive'),
          (34,'B.Paste','user'), (35,'F.Paste','user'),
          (36,'B.SilkS','user','B.Silkscreen'), (37,'F.SilkS','user','F.Silkscreen'),
          (38,'B.Mask','user'), (39,'F.Mask','user'),
          (40,'Dwgs.User','user','User.Drawings'), (41,'Cmts.User','user','User.Comments'),
          (42,'Eco1.User','user','User.Eco1'), (43,'Eco2.User','user','User.Eco2'),
          (44,'Edge.Cuts','user'), (45,'Margin','user'),
          (46,'B.CrtYd','user','B.Courtyard'), (47,'F.CrtYd','user','F.Courtyard'),
          (48,'B.Fab','user'), (49,'F.Fab','user')]

SETUP = '''\t(setup
\t\t(pad_to_mask_clearance 0)
\t\t(allow_soldermask_bridges_in_footprints no)
\t\t(tenting front back)
\t\t(stackup
\t\t\t(layer "F.SilkS" (type "Top Silk Screen"))
\t\t\t(layer "F.Paste" (type "Top Solder Paste"))
\t\t\t(layer "F.Mask" (type "Top Solder Mask") (thickness 0.0254) (epsilon_r 3.8))
\t\t\t(layer "F.Cu" (type "copper") (thickness 0.035))
\t\t\t(layer "dielectric 1" (type "prepreg") (thickness 0.0764) (material "NP-155F 1080 RC67%") (epsilon_r 3.91) (loss_tangent 0.02))
\t\t\t(layer "In1.Cu" (type "copper") (thickness 0.0152))
\t\t\t(layer "dielectric 2" (type "core") (thickness 0.1) (material "NP-155F core") (epsilon_r 4.36) (loss_tangent 0.02))
\t\t\t(layer "In2.Cu" (type "copper") (thickness 0.0152))
\t\t\t(layer "dielectric 3" (type "core") (thickness 0.2104) (material "NP-155F 7628 RC49%") (epsilon_r 4.4) (loss_tangent 0.02)
                (addsublayer) (thickness 0.7) (material "NP-155F core") (epsilon_r 4.53) (loss_tangent 0.02)
                (addsublayer) (thickness 0.2104) (material "NP-155F 7628 RC49%") (epsilon_r 4.4) (loss_tangent 0.02))
\t\t\t(layer "In3.Cu" (type "copper") (thickness 0.0152))
\t\t\t(layer "dielectric 4" (type "core") (thickness 0.1) (material "NP-155F core") (epsilon_r 4.36) (loss_tangent 0.02))
\t\t\t(layer "In4.Cu" (type "copper") (thickness 0.0152))
\t\t\t(layer "dielectric 5" (type "prepreg") (thickness 0.0764) (material "NP-155F 1080 RC67%") (epsilon_r 3.91) (loss_tangent 0.02))
\t\t\t(layer "B.Cu" (type "copper") (thickness 0.035))
\t\t\t(layer "B.Mask" (type "Bottom Solder Mask") (thickness 0.0254) (epsilon_r 3.8))
\t\t\t(layer "B.Paste" (type "Bottom Solder Paste"))
\t\t\t(layer "B.SilkS" (type "Bottom Silk Screen"))
\t\t\t(copper_finish "ENIG")
\t\t\t(dielectric_constraints no)
\t\t)
\t\t(pcbplotparams
\t\t\t(layerselection 0x00010fc_ffffffff)
\t\t\t(plot_on_all_layers_selection 0x0000000_00000000)
\t\t\t(disableapertmacros no) (usegerberextensions no) (usegerberattributes yes)
\t\t\t(usegerberadvancedattributes yes) (creategerberjobfile yes)
\t\t\t(dashed_line_dash_ratio 12.000000) (dashed_line_gap_ratio 3.000000)
\t\t\t(svgprecision 4) (plotframeref no) (mode 1) (useauxorigin no)
\t\t\t(dxfpolygonmode yes) (dxfimperialunits yes) (dxfusepcbnewfont yes)
\t\t\t(psnegative no) (psa4output no) (plot_black_and_white yes)
\t\t\t(sketchpadsonfab no) (plotpadnumbers no) (hidednponfab no)
\t\t\t(sketchdnponfab yes) (crossoutdnponfab yes) (subtractmaskfromsilk no)
\t\t\t(outputformat 1) (mirror no) (drillshape 1) (scaleselection 1)
\t\t\t(outputdirectory "")
\t\t)
\t)'''

def emit_board():
    o = ['(kicad_pcb', '\t(version 20241229)', '\t(generator "odin-tools")',
         '\t(generator_version "9.0")',
         '\t(general\n\t\t(thickness 1.6)\n\t\t(legacy_teardrops no)\n\t)',
         '\t(paper "A3")', '\t(layers']
    for l in LAYERS:
        o.append(f'\t\t({l[0]} "{l[1]}" {l[2]}' + (f' "{l[3]}"' if len(l) > 3 else '') + ')')
    o.append('\t)')
    # Sig / GND / Sig / PWR / GND / Sig, nominal 1.6 mm ENIG.
    # JLC06161H-1080B: https://jlcpcb.com/impedance
    # Material parameters and solver evidence: ref/pcb-impedance.md.
    o.append(SETUP)
    o.append('\t(net 0 "")')
    # rounded rectangular outline
    x1, y1, x2, y2 = X0, Y0, X0 + W, Y0 + H
    seg = lambda ax, ay, bx, by: (f'\t(gr_line (start {ax} {ay}) (end {bx} {by}) '
                                  f'(stroke (width 0.1) (type default)) (layer "Edge.Cuts"))')
    arc = lambda ax, ay, mx, my, bx, by: (f'\t(gr_arc (start {ax} {ay}) (mid {mx} {my}) '
                                          f'(end {bx} {by}) (stroke (width 0.1) (type default)) '
                                          f'(layer "Edge.Cuts"))')
    k = R * (1 - 0.70710678)
    o += [seg(x1+R, y1, x2-R, y1), seg(x2, y1+R, x2, y2-R),
          seg(x2-R, y2, x1+R, y2), seg(x1, y2-R, x1, y1+R),
          arc(x2-R, y1, x2-k, y1+k, x2, y1+R),
          arc(x2, y2-R, x2-k, y2-k, x2-R, y2),
          arc(x1+R, y2, x1+k, y2-k, x1, y2-R),
          arc(x1, y1+R, x1+k, y1+k, x1+R, y1)]
    for tx, ty, txt, sz, layer in (
            (x1+4, y1+5, f'{PRODUCT} HW {HW_VERSION}', 2.0, 'F.SilkS'),
            (x1+4, y1+10, f'{FPGA_PART} + {CONTROLLER_PART}  |  6 layer', 1.5, 'F.Fab')):
        o.append(f'\t(gr_text "{txt}" (at {tx} {ty}) (layer "{layer}") '
                 f'(effects (font (size {sz} {sz}) (thickness {sz/6:.2f})) (justify left)))')
    o.append(')')
    open(OUT, 'w').write('\n'.join(o) + '\n')
    print(f"wrote {OUT}: {W}x{H}mm, 6 layers, ENIG")

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--rules-only', action='store_true',
                        help='update stackup and project rules, preserving board contents')
    args = parser.parse_args()
    if args.rules_only:
        update_stackup()
    else:
        emit_board()
    emit_rules()


if __name__ == '__main__':
    main()
